### ISSUE TITLE
How is the course like?

### ISSUE THREAD

**Issue by abhiML** [Jackal08/QuantInsti-Final-Project-Statistical-Arbitrage#6]

**Comment by Jackal08** [comment]
I really got a lot out of it. I think they have also improved it since I did it. Its a value add.

**Comment by abhiML** [comment]
I have some experience in ML. are the course materials very basic or does it involve fair bit of higher math and finance too?

**Comment by Jackal08** [comment]
I think the courses are as deep as you want them to be. They explain all the things on a high level but then allow students to go much deeper in the areas that they are interested in. They have amazing support staff. If your interested in a field they will assign a mentor / coach to help you build your project in that area.

**Comment by abhiML** [comment]
alright. Thanks for the help
